name: OpenWrt_immortalwrt_24.10

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: configs/immortalwrt_24.10/immortalwrt.config
  DIY_SH: scripts/immortalwrt_24.10/immortalwrt.sh
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-22.04 # 升级到更现代的运行环境
    outputs:
      OPENWRTROOT: ${{ steps.update.outputs.OPENWRTROOT }}
      PLATFORM: ${{ steps.compile.outputs.PLATFORM }}
      TARGET: ${{ steps.compile.outputs.TARGET }}
      SUBTARGET: ${{ steps.compile.outputs.SUBTARGET }}
      FIRMWARE: ${{ steps.compile.outputs.FIRMWARE }}
      GENERATE_STATUS: ${{ steps.generate.outputs.GENERATE_STATUS }}

    steps:
    - uses: actions/checkout@v4

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get -qq update
        sudo apt-get -qq install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip bc zlib1g-dev \
          file wget diffutils dos2unix libtool-bin curl cmake autoconf automake binutils \
          bzip2 libreadline-dev patch gperf lib32gcc1 libc6-dev-i386 subversion \
          flex uglifyjs git-core p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev \
          xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler \
          g++-multilib antlr3 gperf libevent-dev libexpat1-dev libgmp3-dev libmpc-dev \
          libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev swig libtool wget \
          python3 python3-pip python3-ply python3-docutils python3-setuptools rename
        sudo apt-get -qq autoremove --purge
        sudo apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo dd if=/dev/zero of=/swapfile bs=1G count=8 status=none
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - uses: endersonmenezes/free-disk-space@v2
      with:
        remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
      
    - name: Clone Source Code
      working-directory: /workdir
      run: |
        git clone -q $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update Feeds
      id: update
      run: |
        cd /workdir/openwrt
        echo "OPENWRTROOT=$PWD" >> $GITHUB_ENV
        echo "OPENWRTROOT=$PWD" >> $GITHUB_OUTPUT
        mkdir customfeeds
        git clone -q --depth=1 https://github.com/xuanranran/openwrt-package customfeeds/lovepackages
        git clone -q --depth=1 https://github.com/xuanranran/rely customfeeds/loverely
        git clone -q --depth=1 https://github.com/immortalwrt/packages -b $REPO_BRANCH customfeeds/packages
        git clone -q --depth=1 https://github.com/immortalwrt/luci -b $REPO_BRANCH customfeeds/luci
        git clone -q --depth=1 https://github.com/openwrt/routing -b $REPO_BRANCH customfeeds/routing
        git clone -q --depth=1 https://github.com/openwrt/telephony -b $REPO_BRANCH customfeeds/telephony
        chmod +x $GITHUB_WORKSPACE/scripts/*.sh
        chmod +x $GITHUB_WORKSPACE/scripts/immortalwrt_24.10/*.sh
        $GITHUB_WORKSPACE/scripts/immortalwrt_24.10/hook-package.sh
        $GITHUB_WORKSPACE/scripts/immortalwrt_24.10/hook-base.sh
        $GITHUB_WORKSPACE/scripts/immortalwrt_24.10/hook-feeds.sh

    - name: Install Feeds
      run: |
        cd $OPENWRTROOT
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        [ -e $GITHUB_WORKSPACE/files ] && mv $GITHUB_WORKSPACE/files $OPENWRTROOT/files
        [ -e $GITHUB_WORKSPACE/$CONFIG_FILE ] && mv $GITHUB_WORKSPACE/$CONFIG_FILE $OPENWRTROOT/.config
        chmod +x $GITHUB_WORKSPACE/scripts/*.sh
        cd $OPENWRTROOT
        $GITHUB_WORKSPACE/$DIY_SH
        make defconfig

    - name: Download Package
      run: |
        cd $OPENWRTROOT
        make download -j$(nproc)

    - name: Compile Packages
      id: compile
      run: |
        cd $OPENWRTROOT
        make tools/compile -j$(nproc) V=s || exit 1
        make toolchain/compile -j$(nproc) V=s || exit 1
        make target/compile -j$(nproc) V=s || exit 1
        make package/compile -j$(nproc) V=s || exit 1

    - name: Generate Firmware
      id: generate
      run: |
        cd $OPENWRTROOT
        mkdir -p files/etc/uci-defaults/
        cp $GITHUB_WORKSPACE/scripts/immortalwrt_24.10/immortalwrt-init-settings.sh files/etc/uci-defaults/99-init-settings
        make target/install -j$(nproc) V=s || exit 1
        make package/install -j$(nproc) V=s || exit 1
        make checksum
